update-packagist:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:lts
  stage: deploy
  tags:
    - cron
  script:
    - node scripts/update.js
    - git remote set-url origin https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.universetech.cc/golden/frontend/big.js
    - git add package.json
    - |
      git commit --author="universetech_bot <universetech_bot@universetech.cc>" -m "chore: update package.json"
    - git push
    - npm publish --tag $BRANCH
  only:
    - schedules
