update-packagist:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:lts
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_SLUG
  script:
    - npm config set registry https://registry.npmjs.org/
    - npm config set _authToken=$NPM_TOKEN
    - npm publish --tag $BRANCH
  only:
    - dev
    - alpha
    - beta
    - master
